
koji-db:
    image: "postgres:9.4"
    hostname: koji-db
    environment:
        - POSTGRES_DB=koji
        - POSTGRES_USER=koji
        - POSTGRES_PASSWORD=mypassword

koji-hub:
    image: "docker.io/buildchimp/koji-dojo-hub"
    hostname: koji-hub
    volumes:
        - /opt/koji:/opt/koji:rw
        - /opt/koji-clients:/opt/koji-clients:rw
    links:
        - koji-db

koji-client:
    image: "docker.io/buildchimp/koji-dojo-client"
    hostname: koji-client
    volumes_from:
        - koji-hub:rw
    links:
        - koji-hub

